ktor:
  application:
    modules:
      - dev.artisra.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  realm: "Study Session Auth App"
  domain: "https://jwt-provider-domain/"
  secret: "<here-goes-your-secret-key>"
  issuer: "<here-goes-your-issuer>"
  audience: "<here-goes-your-audience>"
