ktor:
  application:
    modules:
      - dev.artisra.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  realm: "Study Session Auth App"
  domain: "https://jwt-provider-domain/"
  secret: "<here-goes-your-secret-key>"
  issuer: "<here-goes-your-issuer>"
  audience: "<here-goes-your-audience>"
  expirationMs: 600000 # 10 minutes but can be configured
database:
  url: "jdbc:mysql://localhost:3306/users_db"
  driver: "com.mysql.cj.jdbc.Driver"
  user: "<here-goes-your-db-username>"
  password: "<here-goes-your-db-password>"